### PR TITLE
Simplify rubocop rules

### PR DESCRIPTION
**Pull request by Cruikshanks**
The bulk of the rules were taken from an old GDS repo which contained their specific rule set (the files have been replaced by [govuk-lint](https://github.com/alphagov/govuk-lint).

The original thinking was to keep our projects in line with those from GDS. However as we have progressed the general feeling in the team is that we would rather move to be closer to the defaults in the [community style guide](https://github.com/bbatsov/ruby-style-guide), with any exceptions being those agreed by the team.

This changes removes the inherited GDS rules, and retains only those currently agreed by the team.

### CODE REVIEW

**Comment by Cruikshanks** [comment]
@reggieb Ok, its seems Travis-CI is building fine but when I run the tests locally I get 4 failures

```text
  1) Failure:
BeforeCommit::RunnerTest#test_run_with_check_failures [/Users/acruikshanks/projects/ea/before_commit/test/before_commit/runner_test.rb:18]:
Expected: false
  Actual: true


  2) Failure:
BeforeCommit::FileManagerTest#test_copy_dir_to_current_removes_existing [/Users/acruikshanks/projects/ea/before_commit/test/before_commit/file_manager_test.rb:36]:
File /Users/acruikshanks/projects/ea/before_commit/test/data/temp/foo should exist


  3) Failure:
BeforeCommit::FileManagerTest#test_copy_dir_to_current_with_dot_file [/Users/acruikshanks/projects/ea/before_commit/test/before_commit/file_manager_test.rb:36]:
File /Users/acruikshanks/projects/ea/before_commit/test/data/temp/foo should exist


  4) Failure:
BeforeCommit::FileManagerTest#test_copy_dir_to_current [/Users/acruikshanks/projects/ea/before_commit/test/before_commit/file_manager_test.rb:36]:
File /Users/acruikshanks/projects/ea/before_commit/test/data/temp/foo should exist

26 runs, 84 assertions, 4 failures, 0 errors, 0 skips
```

I blame sleepiness for getting things confused. Would just like your 💭 on this as to whether this is just a local issue for me.

**Comment by Cruikshanks** [comment]
@autotelik @woodpigeon @autotelik It would be worth getting your 💭 on the new smaller ruleset before this is merged in. Is there anything in `.rubocop.yml` that could go, or that you would want back in (and no you can't disable everything Tom!)?

**Comment by autotelik** [comment]
hey I like rubocop !  I only object to rules that try to turn ruby into python !

**Comment by reggieb** [comment]
I agree with @autotelik - It's the white space rules that are annoying - or sometimes just plain bad. Some examples:

```ruby
foo = bar(
  one: 1,
  two: 2
)
```
Rubocop would accept this alignment of an assignment to a new variable, via a constuctor that requires multiple options. However, to me by lining up the `one` and `two` on `foo` it says to me that those attributes belong to `foo` when in fact they belong to `bar`.

Personally, I'd prefer to write that code like this:


```
foo = bar(
        one: 1,
        two: 2
      )
```


As that make is clear the thing that is being split over the lines are the variables being passed to `bar`.

I also think this is a far better option to the one rubocop enforces:

```ruby
foo = bar( one: 1,
           two: 2 )
```

I also thing that a long lists of assignment pairs can be clearer if you align to the gap between the pairs. For example:

The rubocop enforced way:

```ruby
FactoryGirl.define do
  factory :address, class: "FloodRiskEngine::Address" do
    premises Faker::Address.building_number
    street_address Faker::Address.street_address
    locality Faker::StarWars.planet
    city Faker::Address.city
    postcode Faker::Address.postcode
    county_province_id 1
    country_iso Faker::Address.country_code
    address_type 1
    organisation Faker::Company.name
    state_date 1.year.ago
    blpu_state_code Faker::Lorem.characters(10)
    postal_address_code Faker::Lorem.characters(10)
    logical_status_code Faker::Lorem.characters(10)
  end
end
```

Aligning on the space:

```ruby
FactoryGirl.define do
  factory :address, class: "FloodRiskEngine::Address" do
               premises Faker::Address.building_number
         street_address Faker::Address.street_address
               locality Faker::StarWars.planet
                   city Faker::Address.city
               postcode Faker::Address.postcode
     county_province_id 1
            country_iso Faker::Address.country_code
           address_type 1
           organisation Faker::Company.name
             state_date 1.year.ago
        blpu_state_code Faker::Lorem.characters(10)
    postal_address_code Faker::Lorem.characters(10)
    logical_status_code Faker::Lorem.characters(10)
  end
end
```

**Comment by reggieb** [comment]
Also on the last one, adding some space to the top and bottom of the list adds clarity to where the list of pairs begins and ends:

```ruby
FactoryGirl.define do
  factory :address, class: "FloodRiskEngine::Address" do

               premises Faker::Address.building_number
         street_address Faker::Address.street_address
               locality Faker::StarWars.planet
                   city Faker::Address.city
               postcode Faker::Address.postcode
     county_province_id 1
            country_iso Faker::Address.country_code
           address_type 1
           organisation Faker::Company.name
             state_date 1.year.ago
        blpu_state_code Faker::Lorem.characters(10)
    postal_address_code Faker::Lorem.characters(10)
    logical_status_code Faker::Lorem.characters(10)
    
  end
end
```

**Comment by reggieb** [comment]
While I'm waffling on: I like having a space between a object declaration and the definition of the first method.

The rubocop way

```ruby
class Foo
  def first
    1
  end

  def second
   2
  end
end
```

To me the lack of space between the class declaration and first method implies that the first method has some special association with the class. Surely, if you should not have a space between the class declaration and the first method, you should not have a space between the first and second methods. So should the rubocop enforced styling be:

```ruby
class Foo
  def first
    1
  end
  def second
   2
  end
end
```

Which is just plain ugly.

For me, a definition should have white space around it. So I'd prefer:

```ruby
class Foo

  def first
    1
  end

  def second
   2
  end

end
```

**Comment by autotelik** [comment]
Umm have we actually swapped Ffaker for Faker .. invalidating the existing factories ?

**Comment by autotelik** [comment]
And yeah I think the white space is preferable, don't like method touching class

**Comment by reggieb** [comment]
Faker is the more widely used option, and therefore more likely to be continually maintained. Ffaker was a branch that was created to address a specific problem. To quote the [README](https://github.com/ffaker/ffaker):

> Since those days faker has also been rewritten and the "speed" factor is probably irrelevant now. 
>    ...
> Hopefully some day faker and ffaker will join forces!

Also Faker's documentation seems a lot clearer to me. Compare the README above with the [Faker README](https://github.com/stympy/faker).

Is there some Ffaker functionality that will be needed in the new app?

**Comment by autotelik** [comment]
no i guess the functionality is identical for our needs, just shame perfectly good code has to be changed/rewritten when we had no issues with ffaker at all

**Comment by woodpigeon** [comment]
For me, apart from linting, the main point of rubocop is to encourage code that's well designed and easy to maintain. So just a couple of thoughts:

*Metrics/MethodLength*- Ideally I think this is better at 10 than 20 but we could compromise on 15? Encourages code that's easier to read and maintain

*Metrics/ModuleLength* at 500 is a bit steep - default is 100 (excluding comments) and my preference. Maybe 200 a compromise? Apart from specs, which are already excluded, I can't think of circumstances were a long file would not be improved by refactoring or just breaking it up to make it easier to read. Getting long files noticed sooner rather than later might flag god objects at an early stage and help drive the design

**Comment by autotelik** [comment]
I think I can live with Metrics/ModuleLength of 200

**Comment by woodpigeon** [comment]
Re ffaker/faker - don't have a preference, but I agree with Tom that there is no point changing if it means lost effort for no real gain

**Comment by Cruikshanks** [comment]
One the spaces after class declaration I believe we're covered
```ruby
Style/EmptyLinesAroundModuleBody:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
```
http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/EmptyLinesAroundClassBody

**Comment by Cruikshanks** [comment]
Oh, and regards the **ffaker** / **faker** discussion lets take this out of here into slack

**Comment by Cruikshanks** [comment]
Finally coming back to some of the other spacing questions. I've found this 
```ruby
foo = bar(
  one: 1,
  two: 2
)
```
is fairly common. Having come from a **static** I'm sure this was generally how my big hefty IDE would format things. So unless anyone else on the team feels strongly on this I'd say leave as is.

Do agree with this one though

```ruby
FactoryGirl.define do
  factory :address, class: "FloodRiskEngine::Address" do
               premises Faker::Address.building_number
         street_address Faker::Address.street_address
               locality Faker::StarWars.planet
                   city Faker::Address.city
               postcode Faker::Address.postcode
     county_province_id 1
            country_iso Faker::Address.country_code
           address_type 1
           organisation Faker::Company.name
             state_date 1.year.ago
        blpu_state_code Faker::Lorem.characters(10)
    postal_address_code Faker::Lorem.characters(10)
    logical_status_code Faker::Lorem.characters(10)
  end
end
```
(though I can give or take the spacing). I'll look to see if I can track down the responsible cop to see what options we have or what excluding it leads to. It might just be we have to use the ability to exclude sections of code when we have a large list of assignments like this, but I'll report back in a bit.

**Comment by autotelik** [comment]
yep rubymine agrees with this  ...

foo = bar(
  one: 1,
  two: 2
)

**Comment by reggieb** [comment]
But @autotelik you do it yourself. For example, the Party model `has_many :addresses` declaration in DigitalServicesCore.

```ruby
module DigitalServicesCore
  class DigitalServicesCore::Party < ActiveRecord::Base

    has_many :enrollments
    has_many :contacts

    has_many :addresses,
             through: :contacts, class_name: "DigitalServicesCore::Address", dependent: :restrict_with_exception

    def update_party_type(party_klass)
      # Only update if Type currently nil or base class (Party)
      if(self[:type].nil? || (party_klass < self[:type].constantize))
        self[:type] = party_klass
        self.save
      end
    end

  end
end
```

And the Contact model is full of that style of spreading attribute assignment over multi-lines.

**Comment by autotelik** [comment]
I'm just saying whatever format I enter that foo bar thing rubymine auto formatting turns it into what Alan posted, frankly it doesn't bother me either way as long as rubocop -a auto fixes it

that multi line is because we only have 120 chars  .. so at some point has to go on next line

**Comment by reggieb** [comment]
@autotelik I see. Yes most IDEs will automatically format the code that way, and I agree that this should be the usual style. All I'm saying is that sometimes extra clarity can be gained by moving the attributes to align with another part of the previous line, and it is annoying to have rubocop trying to "correct" that.

**Comment by Cruikshanks** [comment]
Okey dokey. `Style/IndentationConsistency` is the cop that fails the spacing example

```ruby
FactoryGirl.define do
  factory :address, class: "FloodRiskEngine::Address" do
               premises Faker::Address.building_number
         street_address Faker::Address.street_address
               locality Faker::StarWars.planet
                   city Faker::Address.city
               postcode Faker::Address.postcode
     county_province_id 1
            country_iso Faker::Address.country_code
           address_type 1
           organisation Faker::Company.name
             state_date 1.year.ago
        blpu_state_code Faker::Lorem.characters(10)
    postal_address_code Faker::Lorem.characters(10)
    logical_status_code Faker::Lorem.characters(10)
  end
end
```

However turning this off would mean this kind of stuff would pass
```ruby
def foobar
  x = 1
    y = 2
            puts x + y
end
```
So I'm not turning that off. However I found rubocop does find this acceptable.
```ruby
FactoryGirl.define do
  factory :address, class: "FloodRiskEngine::Address" do
    premises            Faker::Address.building_number
    street_address      Faker::Address.street_address
    locality            Faker::StarWars.planet
    city                Faker::Address.city
    postcode            Faker::Address.postcode
    county_province_id  1
    country_iso         Faker::Address.country_code
    address_type        1
    organisation        Faker::Company.name
    state_date          1.year.ago
    blpu_state_code     Faker::Lorem.characters(10)
    postal_address_code Faker::Lorem.characters(10)
    logical_status_code Faker::Lorem.characters(10)
  end
end
```
On the parameter alignment thing `Style/FirstParameterIndentation` is the one on guard. If I disable it it means you're permitted to do any one of these
```ruby
foo = bar(
          one: 1,
          two: 2
)

bar = foo(one: 1,
          two: 2)

hah = car(one: 1,
          two: 2
         )
```
I feel a little uneasy about this as it could lead to inconsistency but we're getting into the realms of [bikeshedding](https://en.wikipedia.org/wiki/Law_of_triviality) so am happy to disable if everyone else is (give this comment a thumbs up response if you want this rule disabled).

**Comment by reggieb** [comment]
This is a good alternative to my pair list format:

```ruby
FactoryGirl.define do
  factory :address, class: "FloodRiskEngine::Address" do
    premises            Faker::Address.building_number
    street_address      Faker::Address.street_address
    locality            Faker::StarWars.planet
    city                Faker::Address.city
    postcode            Faker::Address.postcode
    county_province_id  1
    country_iso         Faker::Address.country_code
    address_type        1
    organisation        Faker::Company.name
    state_date          1.year.ago
    blpu_state_code     Faker::Lorem.characters(10)
    postal_address_code Faker::Lorem.characters(10)
    logical_status_code Faker::Lorem.characters(10)
  end
end
```

**Pull request merged**
