### PR TITLE
Proposals for Rule Changes

### PR DESCRIPTION
**Pull request by autotelik**
1      Disable Style/FormatString:

Why : Although I use it very rarely there are instances where the sprtinf style is useful, for example when storing a formatted string as a template, and passing in strings that can vary with context, for example

```ruby
Templates::RailsForm.reform_style_template % [configuration.model, configuration.form_id]
```

### CODE REVIEW

**Comment by Cruikshanks** [comment]
If its only thing used rarely, would it be better to just disable the rule in the source where you need to

```ruby
# rubocop:disable Style/FormatString
Templates::RailsForm.reform_style_template % [configuration.model, configuration.form_id]
# rubocop:enable Style/FormatString
```
😐 :thought_balloon:

**Comment by autotelik** [comment]
Yeah can do, except it is not bad code. It is useful and legal code. Just a 'style' thing.

**Comment by Cruikshanks** [comment]
Then I'm fine with the exclusion. Shout now 👥 if you think differently!

**Comment by autotelik** [comment]
Settings for Metrics/AbcSize seem a bit low, had lots of complaints about methods like this, which are pretty simple to read, composer type methods where seems little to be gained by trying to split into more and more methods

```ruby
      def extract(html)
        parse(html)

        CopyKit::HtmlConverters::RemoveSpecifiedTags.call(doc, configuration)

        # N.B Because removing tags requires we copy the inner HTML, we have to reparse now or we seem to loose ERB
        # snippets later (when to_html called). nokogiri can't handle erb so the inner html copy has some
        # knock on effect
        parse(to_html)

        CopyKit::HtmlConverters::RemoveBackLink.call(doc, configuration) if configuration.remove_back_links

        html_convert_all(doc, configuration)

        extract_all_tags

        to_html
      end
```

**Comment by Cruikshanks** [comment]
What do you need to raise it to in order to get something like this to pass?

**Comment by autotelik** [comment]
Metrics/AbcSize:
  # The ABC size is a calculated magnitude, so this number can be a Fixnum or
  # a Float.
  Max: 20

Seems to exclude methods like above whilst still failing for moderately complex methods

**Comment by Cruikshanks** [comment]
Going from the default 15 to 20 seems reasonable unless anyone else takes issue with it.

**Comment by Cruikshanks** [comment]
@autotelik I've added a commit to cover the increase in metric size and I reckon that will do us for now on rule changes. I'm giving this the 👍 and feel we don't need to squash the commits, we can keep them separate. But ideally if you could reword your commit to include the reason why then I'd say its ready to ship.

N.B. To do so just use `git rebase -i HEAD~2`, replace `pick` with `r` against the first commit message, expand the commit message, save and then `git push -f`.

**Comment by Cruikshanks** [comment]
@autotelik did you want me to do the reword on that commit? We can then 🚢 this PR.

**Pull request merged**
